### PR TITLE
Feat/enter-shift-enter

### PR DESCRIPTION
**Pull request by romulorod**
This Pull Request feats the enhancement of pressing enter key to move to the next input and shift + enter to move to previous input.

This branch has been rebased with _feat/ctrl-enter_ as it touches the specific part of the code, therefore it's advised to merge that one before merges this one.

If anything to be changed please feel free to contact me so I can assist if needed.

This aims to fix [this issue](https://github.com/LukeberryPi/phived/issues/2)

### CODE REVIEW

**Comment by LukeberryPi** [comment]
the environment preview doesn't seem to support "shift+enter" selecting previous input. could this be related to the (now merged) issue https://github.com/LukeberryPi/phived/issues/1?

**Comment by romulorod** [comment]
> the environment preview doesn't seem to support "shift+enter" selecting previous input. could this be related to the (now merged) issue #1?

It does work perfectly fine to me, may I ask which browser are you using?

**Comment by romulorod** [comment]
Oh no! My bad, hahaha.

I was just pressing shift + tab to get back to previous input (muscle memory, perhaps?).

It has already been fixed and also got rid of the conflicts :D

**Review by LukeberryPi — APPROVED** [review]
works great now! approved and merged

**Pull request merged**
