### PR TITLE
feature: incentive message

### PR DESCRIPTION
**Pull request by ItaloCovas**
Adding incentive messages (it appears in the same place as "phived" logo). They are displayed for 2 seconds and then return to "phived".
No animation added yet, I had some troubles trying to add them because I barely used Tailwind before, if someone has anything to suggest :)

### CODE REVIEW

**Comment by LukeberryPi** [comment]
thank you so much for submitting this, super cool to see this idea in action! the idea of incentives originated from adding a "reward for resolution" when a user completes a task, since the current experience (even though working as intended) is pretty bland. your implementation kills it in this regard, good job! a couple of thoughts:

- the logo will be moving towards the left of the navbar, as it is in most websites. this means that the component you created should be decoupled from <Logo /> (should be a new component);
- contributors raised some UX concerns: there are actions around the website that are irreversible **and** have no confirmation steps. for example, when you click done, the task disappears instantly and cannot be retrieved. this is dangerous as it makes accidental clicks very frustrating (imagine a user accidentaly clicks "clear tasks", they would have to to type them back one by one);
- to deal with this, task completion and task list clearance will display a message exactly as you implemented, but with an **undo button** (https://usehooks.com/usePrevious/ this is what I have in mind)
- for clearing all tasks, the fixed message "tasks cleared" will de displayed.also in the same position + style you suggested
- for task completion, a random incentive message will de displayed exactly as you suggested;

i'm available for any questions you might have, and thanks again for the great PR!

**Comment by ItaloCovas** [comment]
Hey @LukeberryPi, I have pushed those changes.

=> Created a generic component "Message", either for clearing messages or getting they completed.
=> Created the "undo" button beside the text, but didn't implement any undo feature.
=> Created the usePrevious hook.
=> Now the "clear tasks" button is only enabled when we have at least 1 task.
=> Added cursor pointer to the "help" button.
=> Moved "phived" logo to the header, still not responsive, if you could help me with that :)

Thanks!!

**Comment by ItaloCovas** [comment]
By the way i have changed the display time to 3 seconds, with the "undo" button the user experience is better that way.

**Comment by ItaloCovas** [comment]
Realized that in the mobile version the text doesn't show up. Do anyone knows why?

**Comment by LukeberryPi** [comment]
howdy! i commited a quick style adjust for the header. i will address remaining changes soon. this looks very close to what we need to have, great job! it will be merged without the undo button. we will keep the hook and implement undo functionality in a future issue.

> Realized that in the mobile version the text doesn't show up. Do anyone knows why?

it might be "hidden" behind the main tasks component. maybe you can mess around with z-index.
on that note, there seems to be a bit of a layout shift on mobile while displaying our Message component, but we can keep adjusting + iterating. this is a meaningful PR and we have no rush!

thanks again for your contribution and let's keep this moving!

**Review by LukeberryPi — APPROVED** [review]

**Review by LukeberryPi — APPROVED** [review]

**Comment by ItaloCovas** [comment]
Thank you for the help @LukeberryPi, really appreciate that!
I'll contribute more as I can 🚀

**Pull request merged**
