### PR TITLE
feat: Initial support for lint rules

### LINKED ISSUE #23: Configure eslint to standardize code
I love how the project is getting a lot of help from the community, but currently we don't have any tool to provide a code checking to make sure everyone follow the same code style. For example someone can use double quotes, while other prople use single quotes, while another use crasis and so on...

I think we can configure eslint rules for everyone to follow, along with using [lint-staged](https://www.npmjs.com/package/lint-staged) and [husky](https://www.npmjs.com/package/husky) to do that automatically whenever I submit a commit.

### Useful Links
[Lint Staged and Husky](https://valchan.com.br/lint-staged-husky/)
[Lint staged README](https://github.com/okonet/lint-staged/blob/master/README.md)
[Setting ESLint on a React Typescript project](https://andrebnassis.medium.com/setting-eslint-on-a-react-typescript-project-2021-1190a43ffba)

### PR DESCRIPTION
**Pull request by nidib**
Closes #23 

- This PR starts the support of having lint rules to keep the project standardized
- Adds `.nvmrc` for quick node version switch
- Adds `.editorconfig` for major code editors to use the project's standards

### CODE REVIEW

**Review by Nick-Gabe — CHANGES_REQUESTED** [review]
I can imagine this will give conflicts in every PR that's currently open, but it's ok 😅.
Also very great setup, I loved that you took everything into account in the eslintrc.

But could you please also add the [eslint-prettier-plugin](https://www.npmjs.com/package/eslint-plugin-prettier) and also integrate that with husky and lint-staged?
lint-staged for only making changes to the staged files, and husky for executing those changes when any commit is made. In this case, running eslint:

```js
// package.json
"lint-staged": {
  "*.{ts,tsx,js,jsx}": [
    "prettier --write",
    "eslint --fix"
  ]
}
```

**Comment by nidib** [comment]
> But could you please also add the [eslint-prettier-plugin](https://www.npmjs.com/package/eslint-plugin-prettier) and also integrate that with husky and lint-staged? lint-staged for only making changes to the staged files, and husky for executing those changes when any commit is made. In this case, running eslint:

I honestly don't know how to set those up :( as I never did it before. Would you mind stepping in and commit those implementations?

We could also if agreed, have another PR just for that. Whatever you prefer

**Review by LukeberryPi — APPROVED** [review]
i will prioritize non-feature pr's for now, since there are still untracked issues with website access. vitest + ci next.

**Comment by LukeberryPi** [comment]
@Nick-Gabe sorry if i generated some conflicts with already opened prs, just trying to clean the house up and merge quality of lif epull requests before features. let me know if i can help with anything!

**Pull request merged**
